name: Build binaries (manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build (branch, tag, or SHA)"
        required: false
        default: main

permissions:
  contents: write

jobs:
  call-release-build:
    uses: ./.github/workflows/release.yml
    with:
      build_only: "true"
    secrets: inherit
